title: tikape syksy 2023 vastaukset
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-remote-theme

toc:
    enabled: true
    h_min: 1
    h_max: 3

markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: thankful_eyes

markdown_ext:             markdown,mkdown,mkdn,mkd,md


collections:
  pages:
    output: true
    permalink: /:collection/:path/


    
destination:      ./_site
incremental:      false
regenerate:       true